"""finished

Revision ID: 905047af89d0
Revises: 4c733cc2179f
Create Date: 2022-03-24 11:08:04.754254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '905047af89d0'
down_revision = '4c733cc2179f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('finished', sa.Boolean(), nullable=True))
    op.drop_column('tasks', 'is_finished')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('is_finished', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('tasks', 'finished')
    # ### end Alembic commands ###
